import { inter, notoSansKR, orbitron } from "@/lib/fonts";
import AuthProvider from "@/providers/AuthProvider";
import Header from "@/components/header";
import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.variable, orbitron.variable, notoSansKR.variable, "antialiased")}>
        <AuthProvider>
          <Header />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
